### ISSUE TITLE
RHEV Refresh Fails

### ISSUE THREAD

**Issue by ilackarms** [ManageIQ/manageiq-providers-ovirt#149]
I've been unable to do a refresh/inventory collect using the ManageIQ ovirt provider. Credentials and URL are correct. Refresh fails with the error `Failed to fetch attributes for vm`

Stack trace from evm log:

```
---] E, [2017-11-16T20:48:44.787987 #21589:3fdcce82b12c] ERROR -- : MIQ(MiqQueue#deliver) Message id: [18845], Error: [Failed to fetch attributes for vm]
[----] E, [2017-11-16T20:48:44.788415 #21589:3fdcce82b12c] ERROR -- : [EmsRefresh::Refreshers::EmsRefresherMixin::PartialRefreshError]: Failed to fetch attributes for vm  Method:[block in method_missing]
[----] E, [2017-11-16T20:48:44.788842 #21589:3fdcce82b12c] ERROR -- : /root/.rbenv/manageiq/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:50:in `refresh'
/root/.rbenv/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:9:in `refresh'
/root/.rbenv/manageiq/app/models/ems_refresh.rb:95:in `block in refresh'
/root/.rbenv/manageiq/app/models/ems_refresh.rb:94:in `each'
/root/.rbenv/manageiq/app/models/ems_refresh.rb:94:in `refresh'
/root/.rbenv/manageiq/app/models/miq_queue.rb:449:in `block in dispatch_method'
/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/root/.rbenv/manageiq/app/models/miq_queue.rb:448:in `dispatch_method'
/root/.rbenv/manageiq/app/models/miq_queue.rb:425:in `block in deliver'
/root/.rbenv/manageiq/app/models/user.rb:253:in `with_user_group'
/root/.rbenv/manageiq/app/models/miq_queue.rb:425:in `deliver'
/root/.rbenv/manageiq/app/models/miq_queue_worker_base/runner.rb:104:in `deliver_queue_message'
/root/.rbenv/manageiq/app/models/miq_queue_worker_base/runner.rb:134:in `deliver_message'
/root/.rbenv/manageiq/app/models/miq_queue_worker_base/runner.rb:152:in `block in do_work'
/root/.rbenv/manageiq/app/models/miq_queue_worker_base/runner.rb:146:in `loop'
/root/.rbenv/manageiq/app/models/miq_queue_worker_base/runner.rb:146:in `do_work'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:329:in `block in do_work_loop'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:326:in `loop'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:326:in `do_work_loop'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:153:in `run'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:127:in `start'
/root/.rbenv/manageiq/app/models/miq_worker/runner.rb:22:in `start_worker'
/root/.rbenv/manageiq/app/models/miq_worker.rb:357:in `block in start_runner_via_fork'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/root/.rbenv/manageiq/app/models/miq_worker.rb:355:in `start_runner_via_fork'
/root/.rbenv/manageiq/app/models/miq_worker.rb:349:in `start_runner'
/root/.rbenv/manageiq/app/models/miq_worker.rb:396:in `start'
/root/.rbenv/manageiq/app/models/miq_worker.rb:266:in `start_worker'
/root/.rbenv/manageiq/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/root/.rbenv/manageiq/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/root/.rbenv/manageiq/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/root/.rbenv/manageiq/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/root/.rbenv/manageiq/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/root/.rbenv/manageiq/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/root/.rbenv/manageiq/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/root/.rbenv/manageiq/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/root/.rbenv/manageiq/app/models/miq_server.rb:329:in `block in monitor'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-bc37126c25d0/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-bc37126c25d0/lib/gems/pending/util/extensions/miq-benchmark.rb:28:in `realtime_block'
/root/.rbenv/manageiq/app/models/miq_server.rb:329:in `monitor'
/root/.rbenv/manageiq/app/models/miq_server.rb:351:in `block (2 levels) in monitor_loop'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-bc37126c25d0/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-bc37126c25d0/lib/gems/pending/util/extensions/miq-benchmark.rb:35:in `realtime_block'
/root/.rbenv/manageiq/app/models/miq_server.rb:351:in `block in monitor_loop'
/root/.rbenv/manageiq/app/models/miq_server.rb:350:in `loop'
/root/.rbenv/manageiq/app/models/miq_server.rb:350:in `monitor_loop'
/root/.rbenv/manageiq/app/models/miq_server.rb:234:in `start'
/root/.rbenv/manageiq/lib/workers/evm_server.rb:27:in `start'
/root/.rbenv/manageiq/lib/workers/evm_server.rb:48:in `start'
/root/.rbenv/manageiq/lib/workers/bin/evm_server.rb:4:in `<main>'
[----] I, [2017-11-16T20:48:44.789191 #21589:3fdcce82b12c]  INFO -- : MIQ(MiqQueue#delivered) Message id: [18845], State: [error], Delivered in [41.542988239] seconds
````

**Comment by oourfali** [comment]
Can you please specify what version are you working with? Can you please attach complete logs?

@pkliczew can you please take a look?

**Comment by oourfali** [comment]
@pkliczewski

**Comment by ilackarms** [comment]
version: ManageIQ/manageiq#6bce23f7cb759fbb22d1c434429e1fd48a406e11

complete logs are 126MB; [I've shared them through Google Docs](https://drive.google.com/a/redhat.com/file/d/1IJQNPEntJMylD4kQ0B9b7N_BhpHtWwZD/view?usp=sharing) (however not sure if that's ideal). If there's a subsection you'd like to see let me know, I'll paste in a gist

**Comment by pkliczewski** [comment]
@ilackarms Please grant me access to the logs I would like to take a look.

**Comment by pkliczewski** [comment]
I noticed that the issue was already reported [here](https://bugzilla.redhat.com/1513528). Will let you know when the fix is available.

**Comment by ilackarms** [comment]
ccing @simon3z

**Comment by pkliczewski** [comment]
The latest code works fine. Please see the [bug](https://bugzilla.redhat.com/1513528) for more details.
