### ISSUE TITLE
UiWorker trying to talk to the actual provider

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-providers-ovirt#369]
No code run from the UI should talk to the provider directly.

Right now, trying to display a VM provisioning screen for an ovirt template (Compute > Infra > VM, toolbar Lifecycle > Provisio, pick ovirt template, press Continue) leads to:

```
[----] I, [2019-05-16T12:41:36.925232 #30570:2affaa46d8fc]  INFO -- : Started POST "/vm_infra/pre_prov?button=continue" for ::1 at 2019-05-16 12:41:36 +0000
[----] I, [2019-05-16T12:41:36.952298 #30570:2affaa46d8fc]  INFO -- : Processing by VmInfraController#pre_prov as JS
[----] I, [2019-05-16T12:41:36.952382 #30570:2affaa46d8fc]  INFO -- :   Parameters: {"button"=>"continue"}
[----] F, [2019-05-16T12:41:44.783372 #30570:2affaa46d8fc] FATAL -- : Error caught: [OvirtSDK4::AuthError] Error during SSO authentication: access_denied: Cannot authenticate user 'admin@internal': Unable to log in. Verify your login information or contact the system administrator..
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:473:in `create_access_token'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:643:in `internal_send'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `block in send'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `synchronize'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `send'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/service.rb:191:in `internal_get'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/services.rb:33313:in `list'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-ovirt-679eebaaabf9/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:910:in `block in get_vnic_profiles_in_cluster'
/home/himdel/manageiq/app/models/ext_management_system.rb:483:in `with_provider_connection'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-ovirt-679eebaaabf9/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:909:in `get_vnic_profiles_in_cluster'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-ovirt-679eebaaabf9/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:867:in `private_load_allowed_networks'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-ovirt-679eebaaabf9/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:113:in `load_allowed_networks'
/home/himdel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-ovirt-679eebaaabf9/app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb:230:in `load_allowed_vlans'
/home/himdel/manageiq/app/models/miq_provision_virt_workflow.rb:233:in `available_vlans_and_hosts'
/home/himdel/manageiq/app/models/miq_provision_virt_workflow.rb:220:in `allowed_vlans'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:287:in `get_field'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `block in get_all_fields'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `each_key'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `get_all_fields'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:102:in `block in init_from_dialog'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:101:in `each'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:101:in `init_from_dialog'
/home/himdel/manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:844:in `prov_set_form_vars'
/home/himdel/manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:224:in `prov_edit'
/home/himdel/manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:104:in `pre_prov'
```

A similar problem is happening in Services > Catalogs > Service Catalogs accordion, when you click on an ovirt service:

```
Error caught: [OvirtSDK4::ConnectionError] Can't send request: Couldn't resolve host name
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:525:in `get_sso_response'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:468:in `create_access_token'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:643:in `internal_send'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `block in send'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `synchronize'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/connection.rb:203:in `send'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/service.rb:191:in `internal_get'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ovirt-engine-sdk-4.2.5/lib/ovirtsdk4/services.rb:33313:in `list'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-ovirt-a86dcf2019da/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:910:in `block in get_vnic_profiles_in_cluster'
/home/himdel/manageiq/app/models/ext_management_system.rb:483:in `with_provider_connection'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-ovirt-a86dcf2019da/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:909:in `get_vnic_profiles_in_cluster'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-ovirt-a86dcf2019da/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:867:in `private_load_allowed_networks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-ovirt-a86dcf2019da/app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb:113:in `load_allowed_networks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-ovirt-a86dcf2019da/app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb:230:in `load_allowed_vlans'
/home/himdel/manageiq/app/models/miq_provision_virt_workflow.rb:233:in `available_vlans_and_hosts'
/home/himdel/manageiq/app/models/miq_provision_virt_workflow.rb:220:in `allowed_vlans'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:287:in `get_field'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `block in get_all_fields'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `each_key'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:274:in `get_all_fields'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:102:in `block in init_from_dialog'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:101:in `each'
/home/himdel/manageiq/app/models/miq_request_workflow.rb:101:in `init_from_dialog'
/home/himdel/manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:788:in `prov_set_show_vars'
/home/himdel/manageiq-ui-classic/app/controllers/catalog_controller.rb:1730:in `get_node_info_handle_leaf_node'
/home/himdel/manageiq-ui-classic/app/controllers/catalog_controller.rb:1796:in `get_node_info'
/home/himdel/manageiq-ui-classic/app/controllers/catalog_controller.rb:1900:in `replace_right_cell'
/home/himdel/manageiq-ui-classic/app/controllers/application_controller/explorer.rb:177:in `tree_select'
/home/himdel/manageiq-ui-classic/app/controllers/catalog_controller.rb:275:in `x_show'
```

**Comment by borod108** [comment]
Hah - apparently this was already reported in a BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1576509

**Comment by himdel** [comment]
Looks like https://github.com/ManageIQ/manageiq-providers-ovirt/pull/401 should fix this one.
