### ISSUE TITLE
Can't refresh oVirt 4.2 provider

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-ovirt#456]
When I try to refresh an oVirt 4.2 provider, it gives me the following error:
```
[----] E, [2020-01-09T14:48:37.324676 #61496:3719a0] ERROR -- : [NoMethodError]: undefined method `external_provider' for nil:NilClass  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2020-01-09T14:48:37.324856 #61496:3719a0] ERROR -- : /home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:44:in `id_of_external_network?'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:519:in `block in vm_hardware_guest_devices'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:511:in `each'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:511:in `vm_hardware_guest_devices'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:439:in `vm_hardware'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:400:in `block in vms'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:348:in `each'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:348:in `vms'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb:11:in `parse'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/inventory.rb:42:in `block in parse'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/inventory.rb:39:in `each'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/inventory.rb:39:in `parse'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/infra_manager/refresher.rb:57:in `block in parse_targeted_inventory'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:28:in `realtime_block'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-providers-ovirt-c544028e4aea/app/models/manageiq/providers/redhat/infra_manager/refresher.rb:56:in `parse_targeted_inventory'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:92:in `block in refresh_targets_for_ems'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:28:in `realtime_block'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:91:in `refresh_targets_for_ems'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block (2 levels) in refresh'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/home/skateman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/manageiq-gems-pending-255ba904f052/lib/gems/pending/util/extensions/miq-benchmark.rb:35:in `realtime_block'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block in refresh'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:31:in `each'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:31:in `refresh'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/ems_refresh.rb:93:in `block in refresh'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/ems_refresh.rb:92:in `each'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/ems_refresh.rb:92:in `refresh'
/home/skateman/Repositories/ManageIQ/manageiq/app/models/miq_queue.rb:480:in `block in dispatch_method'

```

**Comment by borod108** [comment]
@skateman do you have that ovirt available somewhere, I will merge the fix @agrare did anyway, but I would really like to understand better how it happened in the first place tomorrow.

**Comment by agrare** [comment]
@borod108 it is an internal RH system, I'll DM you the details
