### ISSUE TITLE
Metrics auth validation fails with Validation failed: invalid, undefined method `async_exec' for nil:NilClass

### ISSUE THREAD

**Issue by zackary-deems** [ManageIQ/manageiq-providers-ovirt#580]
Infrastructure Management 2.3.0 (MiQ Morphy) while setting up a RHV 4.4 provider, fails on validation of the metrics datastore credentials.  In the UI it appears to always return 'Valid', but in the evm.log it shows validation failed with the above... and does so as a WARN, not an error.

**Comment by zackary-deems** [comment]
Attaching the last 5000 lines of the evm.log
[evm.sample.log](https://github.com/ManageIQ/manageiq-providers-ovirt/files/7636386/evm.sample.log)

**Comment by agrare** [comment]
Thanks for the logs @zackary-deems, I don't see the exception that you note here in this log.  Can you check if it was maybe in the previous check?

**Comment by zackary-deems** [comment]
[evm.sample.log](https://github.com/ManageIQ/manageiq-providers-ovirt/files/7636730/evm.sample.log)

**Comment by agrare** [comment]
Thanks @zackary-deems it looks like the ovirt code is swallowing the backtrace, can you add the following code and re-run the verify task?

```
cd /var/www/miq/vmdb
bundle show manageiq-providers-ovirt
```

This will tell you what directory the ovirt provider is in, e.g. mine outputs `/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-ovirt-7f18ec90ba85` for a master appliance.

Then open this file `app/models/manageiq/providers/redhat/infra_manager/api_integration.rb` and add this line:
```
     def handle_credentials_verification_error(err)
+      _log.log_backtrace(err)
       case err
```

Once that is saved run `systemctl restart evmserverd` and re-try the verification.  We should get a backtrace in the evm.log after that.

**Comment by agrare** [comment]
It sounds like a bug coming from ovirt_metrics since async_exec is a postgres gem method and ovirt_metrics does some weird active record connection adapter magic

**Comment by agrare** [comment]
The `async_exec` backtrace is:
```
"/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:728:in `block (2 levels) in log'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:727:in `block in log'",
 "/home/grare/adam/.gem/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `log'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:242:in `client_min_messages='",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:771:in `configure_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:256:in `initialize'",
 "/home/grare/adam/src/manageiq/manageiq/config/initializers/postgres_required_versions.rb:3:in `initialize'",
 "/home/grare/adam/.gem/gems/ovirt_metrics-3.0.2/lib/active_record/connection_adapters/ovirt_postgresql_adapter.rb:14:in `new'",
 "/home/grare/adam/.gem/gems/ovirt_metrics-3.0.2/lib/active_record/connection_adapters/ovirt_postgresql_adapter.rb:14:in `ovirt_postgresql_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_handling.rb:221:in `retrieve_connection'",
 "/home/grare/adam/.gem/gems/activerecord-6.0.4.1/lib/active_record/connection_handling.rb:189:in `connection'",
 "/home/grare/adam/.gem/gems/ovirt_metrics-3.0.2/lib/ovirt_metrics.rb:46:in `connected?'",
 "/home/grare/adam/src/manageiq/manageiq-providers-ovirt/app/models/manageiq/providers/redhat/infra_manager/api_integration.rb:364:in `check_connect_metrics'",
 "/home/grare/adam/src/manageiq/manageiq-providers-ovirt/app/models/manageiq/providers/redhat/infra_manager/api_integration.rb:273:in `raw_connect'",
 "/home/grare/adam/src/manageiq/manageiq-providers-ovirt/app/models/manageiq/providers/redhat/infra_manager/api_integration.rb:232:in `verify_credentials'",
 "/home/grare/adam/src/manageiq/manageiq/app/models/mixins/verify_credentials_mixin.rb:55:in `verify_credentials?'",
```

**Comment by agrare** [comment]
This is fixed by https://github.com/ManageIQ/ovirt_metrics/pull/38

**Comment by Fryguy** [comment]
We should technically bump the minimum version of ovirt_metrics before we declare this "fixed"

**Comment by agrare** [comment]
Yeah good point

**Comment by agrare** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/584
