### ISSUE TITLE
After Oparin upgrade provisioning not working anymore

### ISSUE THREAD

**Issue by Jonathan-Caruana** [ManageIQ/manageiq-providers-ovirt#651]
Hi,

I upgraded our MiQ instance from Najdorf to Oparin recently and when i try to provision a VM using a template the VM is correctly create on oVirt side but never boot up and so never play Cloud init script.

Here is the situation on MiQ side : 

![image](https://github.com/ManageIQ/manageiq-providers-ovirt/assets/95340581/1470dbdf-960a-4e09-b7af-91fc96113da7)

How can i know what's is going on?

Regards,

**Comment by Jonathan-Caruana** [comment]
I found something maybe it's interesting : 


> Sep 04 15:03:16 MIQ evm[1751232]: ERROR -- evm: MIQ(MiqWorker::Runner) ID [869016] PID [1751232] GUID [803a089a-6951-43a8-af70-cfbb9ea696d0] An unhandled error has occurred: Couldn't find ExtManagementSystem without an ID
>                                                                /opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation/finder_methods.rb:431:in `find_with_ids'
>                                                                /opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation/finder_methods.rb:69:in `find'
>                                                                /opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/querying.rb:21:in `find'
>                                                                /opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/core.rb:177:in `find'
>                                                                /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresh_worker/runner.rb:3:in `after_initialize'
>                                                                /var/www/miq/vmdb/app/models/miq_worker/runner.rb:44:in `initialize'
>                                                                lib/workers/bin/run_single_worker.rb:128:in `new'
>                                                                lib/workers/bin/run_single_worker.rb:128:in `<main>'
> Sep 04 15:03:16 MIQ ruby[1751232]: ERROR: An unhandled error has occurred: Couldn't find ExtManagementSystem without an ID. See log for details.

@agrare Can you me you the journalctl command to get all logs related to my request? 

Regards,

**Comment by Jonathan-Caruana** [comment]
I found something else during another deployment for testing, and i guess all "UNKNOWN" are not normal?

> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: User [admin] with current group ID [1] name [Tenant My Company access]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Instantiating [/System/Process/Event?EventStream%3A%3Aevent_stream=5651499&Host%3A%3Ahost=27&MiqServer%3A%3Amiq_server=2&User%3A%3Auser=1&event_id=5651499&event_stream_id=5651499&event_type=UNKNOWN&host_id=27&object_name=Event&vmdb_object_type=event_stream]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Updated namespace [/System/Process/Event?EventStream%3A%3Aevent_stream=5651499&Host%3A%3Ahost=27&MiqServer%3A%3Amiq_server=2&User%3A%3Auser=1&event_id=5651499&event_stream_id=5651499&event_type=UNKNOWN&host_id=27&object_name=Event&vmdb_object_type=event_stream  ManageIQ/System]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Following Relationship [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Updated namespace [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create  ManageIQ/System/Event/EmsEvent]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Instance [/ManageIQ/System/Event/EmsEvent/RHEVM/UNKNOWN] not found in MiqAeDatastore - trying [.missing]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Followed  Relationship [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: User [admin] with current group ID [1] name [Tenant My Company access]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Instantiating [/System/Process/Event?EventStream%3A%3Aevent_stream=5651500&Host%3A%3Ahost=28&MiqServer%3A%3Amiq_server=2&User%3A%3Auser=1&event_id=5651500&event_stream_id=5651500&event_type=UNKNOWN&host_id=28&object_name=Event&vmdb_object_type=event_stream]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Updated namespace [/System/Process/Event?EventStream%3A%3Aevent_stream=5651500&Host%3A%3Ahost=28&MiqServer%3A%3Amiq_server=2&User%3A%3Auser=1&event_id=5651500&event_stream_id=5651500&event_type=UNKNOWN&host_id=28&object_name=Event&vmdb_object_type=event_stream  ManageIQ/System]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Following Relationship [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Updated namespace [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create  ManageIQ/System/Event/EmsEvent]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Instance [/ManageIQ/System/Event/EmsEvent/RHEVM/UNKNOWN] not found in MiqAeDatastore - trying [.missing]
> Sep 04 16:50:03 MIQ automation[2759]:  INFO -- automation: Followed  Relationship [miqaedb:/System/Event/EmsEvent/RHEVM/UNKNOWN#create]


Regards,

**Comment by Jonathan-Caruana** [comment]
Hello @agrare 

Sorry for the delay.

Yes on MIQ UI i can see the VM and the state is good (because after provisioning it never goes powered on to run the cloud init script)
![image](https://github.com/ManageIQ/manageiq-providers-ovirt/assets/95340581/87412c99-0af6-47b1-a049-f761d87dff2f)


Tell me if  you need more test or a new provisioning try.

Regards,

**Comment by Jonathan-Caruana** [comment]
Hello @agrare  

I have tested to put the patch manually and try a new deployment and now the new vm is correctly power on by MiQ but the cloud-init script is never runned.

I run my test on clone of our MiQ instance (Najdorf) and when i run exactly the same deployment on Najdorf (name, storage, network etc..) and all works fine.

Do you know if it's related to this initial issue?

**Comment by Jonathan-Caruana** [comment]
Hello,

Do you need more informations or tests from me to help to handle this issue?

Regards,
